version: "3.8"
services:
  bd_witnesses:
    image: postgres:15
    restart: always
    volumes:
      - db_caja:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
volumes:
  db_caja:
